export default {
  companies: [],
  technologies: [
    'Python',
    'SQL',
    'PySpark',
    'Apache Spark',
    'Snowflake',
    'AWS',
    'GCP',
    'Apache Airflow',
    'dbt',
    'Kafka',
    'PostgreSQL',
    'Terraform',
    'Docker',
    'Kubernetes',
  ],
  otherProficiencies: [
    'ETL/ELT Pipelines',
    'Data Warehouse Architecture',
    'Cloud Migration',
    'Data Quality Frameworks',
    'Pipeline Monitoring',
    'Data Modeling',
    'Stream Processing',
    'Batch Processing',
    'Business Analytics',
    'Operations Research',
    'Applied Statistics',
  ],
}
